
 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Reporte consolidacion';
 $subtitle= 'Informe de consolidacion';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">
                        <p>Lista de Contenedores actualmente registrados. Eliga editar o Eliminar</p>
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
        <hr>
        <a class="btn btn-success btn-sm" href="<?php echo $this->url('admin-contenedor', array('action'=>'agregar'));?>">Agregar inspeccion</a>
                    

      <!-- Table -->
                    <div class="table-responsive">
          
                <table class="table table-hover table-condensed">
                    <thead>
                        <tr>
                            
                            <th>Fecha</th>
                            <th>Turno</th>
                            <th>Inspector</th>
                            <th>Bodega</th>
                            <th>Exportador</th>
                            <th>Producto</th>
                            <th>ID Contenedor</th>
                            <th>Lote</th>
                            <th>Observaciones</th>
                            <th>Tipo</th>
                            <th>Estado</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                            <?php foreach ($contenedor as $m) : ?>
                            <tr>

                                <td><?php echo $this->escapeHtml($m->hora);?></td>
                                <td><?php echo $this->escapeHtml($m->turno);?></td>
                                <td><?php echo $this->escapeHtml($m->usuario);?></td>
                                <td><?php echo $this->escapeHtml($m->bodega);?></td>
                                <td><?php echo $this->escapeHtml($m->exportador);?></td>
                                <td><?php echo $this->escapeHtml($m->producto);?></td>
                                <td><?php echo $this->escapeHtml($m->contenedor);?></td>
                                <td><?php echo $this->escapeHtml($m->lote);?></td>
                                <td><?php echo $this->escapeHtml($m->observaciones);?></td>
                                <td><?php echo $this->escapeHtml($m->tipo);?></td>
                                
                                <td>
                                    <a class="btn btn-warning btn-xs" href="<?php echo $this->url('admin-contenedor',
                                        array('action'=>'editar', 'id' => $m->id_cont));?>">Editar</a>
                                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('admin-contenedor',
                                        array('action'=>'borrar', 'id' => $m->id_cont));?>">Borrar</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                    </tbody>
                 </table>        
           </div>
                    </div>
                </div>
        </div>
    </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
</div>     
            
            
            
      
 
            
            
            
      