
 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Usuario';
 $subtitle= 'Borrar Usuario';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">

 <p>Estas seguro que deseas borrar 
     '<?php echo $this->escapeHtml($usuario->nombre); ?>
     <?php echo $this->escapeHtml($usuario->apellido); ?>'?
 </p>
 <?php
 $url = $this->url('admin-usuario', array(
     'action' => 'borrar',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $usuario->id_usuario; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
 
</div>
</div>
</div>
</div>
</div>  