 
<?php
$this->headTitle("Login usuarios");
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>


 <fieldset>
      <div class="form-group">
          <?php
            $email = $form->get('email');
            echo $this->formInput($email);
            if(isset($error["email"])){
              echo $error["email"]['emailAddressInvalidHostname'];
            }
          ?>
      </div>
      <div class="form-group">
          <?php
                $pass = $form->get('password');
                echo $this->formInput($pass);
                echo $this->formElementErrors($pass);
            ?> 
          
      </div>
     <!--
      <div class="checkbox">
        <label>
        <input name="remember" type="checkbox" value="Remember Me">Remember Me
        </label>
      </div>-->
      <!-- Change this to a button or input when using this as a form -->
      <?php
echo $this->flashMessenger()->render();
 
echo $this->formElement($form->get('submit'));

?>
      <div class="form-group">
          <center>
              <hr>
           <?php 
           echo $recaptcha->getHTML();
           echo $this->form()->closeTag();
           ?>
          </center>
      </div>
</fieldset>






                          
                        