 <?php


 $title = 'Inspeccion';
 $subtitle= 'Agregar Inspeccion Lotes';
 $this->headTitle($title);
 ?>

<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    

        
  
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">
                     
        
                    


<!-- CONTENIDO DE CLIENTES -->                        
                        
<?php
 $form->setAttribute('action', $this->url('admin-lote', array('action' => 'agregar')));
 $form->setAttribute('role','form');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>   
<div class="row">
    <div class="col-lg-12">
        <div class="col-xs-10">
            
            <div class="col-sm-1">
                <?php
                
                if($this->identity()){
                $iden = $this->identity();
                echo $iden->tipo." : ";
                ?>
           </div>
          <div class="col-sm-11">
                
               <?php
               
                            
                            
                            
                            echo $iden->nombre." ". $iden->apellido;
                    }
                    
                    
               ?>
          </div>
        </div>
        <div class="col-xs-2">
           <?php date_default_timezone_set ('America/Santiago');?>
            <?php echo "Fecha: ";?>
            <?php echo date('d-m-Y h:i:s');?>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-lg-12">
        <div class="col-lg-6">
           <div class="form-group">
                <label for="turno" class="col-sm-2 control-label">Turno</label>
                <div class="col-sm-10">
                  <?php
                echo $this->formHidden($form->get('id_lote'));
                $turno = $form->get('turno');
                echo $this->formSelect($turno);
                echo $this->formElementErrors($turno);
                ?>
                </div>
           </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <label for="tipo" class="col-sm-3 control-label">Tipo de inspeccion</label>
                <div class="col-sm-9">
                    <?php
                        $tipo_inspeccion = $form->get('tipo');
                        echo $this->formSelect($tipo_inspeccion);
                        echo $this->formElementErrors($tipo_inspeccion);
                    ?>
                </div>
                
            </div>
        </div>
    </div>
</div>

<hr>
   <div class="form-group">
    <label for="nro_bodega" class="col-sm-2 control-label">Bodega </label>
    <div class="col-sm-10">
      <?php
    $bodega = $form->get('nro_bodega');
    echo $this->formSelect($bodega);
    echo $this->formElementErrors($bodega);
    ?>
    </div>
  </div>
  <div class="form-group">
    <label for="producto" class="col-sm-2 control-label">Material</label>
    <div class="col-sm-10">
      <?php
    $material = $form->get('producto');
    echo $this->formSelect($material);
    echo $this->formElementErrors($material);
    ?>
    </div>
  </div>
   <div class="form-group">
    <label for="nave" class="col-sm-2 control-label">Nave</label>
    <div class="col-sm-10">
      <?php
    $nave = $form->get('nave');
    echo $this->formSelect($nave);
    echo $this->formElementErrors($nave);
    ?>
    </div>
  </div>
<div class="form-group">
    <label for="cliente" class="col-sm-2 control-label">Cliente</label>
    <div class="col-sm-10">
      <?php
    $cliente = $form->get('id_cliente');
    echo $this->formSelect($cliente);
    echo $this->formElementErrors($cliente);
    ?>
    </div>
  </div>
<div class="form-group">
    <label for="destino" class="col-sm-2 control-label">Destino</label>
    <div class="col-sm-10">
      <?php
    $destino = $form->get('destino');
    echo $this->formInput($destino);
    echo $this->formElementErrors($destino);
    ?>
    </div>
  </div>
<div class="form-group">
    <label for="numero_entrega" class="col-sm-2 control-label">Numero de entrega</label>
    <div class="col-sm-10">
      <?php
    $numero_entrega = $form->get('numero_entrega');
    echo $this->formInput($numero_entrega);
    echo $this->formElementErrors($numero_entrega);
    ?>
    </div>
  </div>

<div class="form-group">
    <label for="codigo_sap" class="col-sm-2 control-label">Codigo Sap</label>
    <div class="col-sm-10">
      <?php
    $codigo_sap = $form->get('codigo_sap');
    echo $this->formInput($codigo_sap);
    echo $this->formElementErrors($codigo_sap);
    ?>
    </div>
  </div>
<div class="form-group">
    <label for="numero_lote" class="col-sm-2 control-label">Numero de lote</label>
    <div class="col-sm-10">
      <?php
    $numero_lote = $form->get('numero_lote');
    echo $this->formInput($numero_lote);
    echo $this->formElementErrors($numero_lote);
    ?>
</div>
      </div>
<div class="damage form-group">
    <label for="pieza_danada" class="col-sm-2 control-label">Piezas dañadas</label>
    <div class="col-sm-10">
      <?php
    $pieza_danada = $form->get('pieza_danada');
    echo $this->formInput($pieza_danada);
    echo $this->formElementErrors($pieza_danada);
    ?>
</div>    
  </div>
<div class="damage form-group">
    <label for="pieza_paquete" class="col-sm-2 control-label">Piezas paquete</label>
    <div class="col-sm-10">
      <?php
    $pieza_paquete = $form->get('pieza_paquete');
    echo $this->formInput($pieza_paquete);
    echo $this->formElementErrors($pieza_paquete);
    ?>
</div>    
  </div>

<div class="form-group">
    <label for="estado" class="col-sm-2 control-label">Estado</label>
    <div class="col-sm-10">
      <?php
    $estado = $form->get('estado');
    echo $this->formInput($estado);
    echo $this->formElementErrors($estado);
    ?>
</div>  
</div>
<div class="form-group">
    <label for="observaciones" class="col-sm-2 control-label">Observaciones</label>
    <div class="col-sm-10">
      <?php
    $observaciones = $form->get('observaciones');
    echo $this->formInput($observaciones);
    echo $this->formElementErrors($observaciones);
    ?>
</div>  
</div>
<div class="form-group">
    <label for="image-file" class="col-sm-2 control-label">Imagen</label>
    <div class="col-sm-10">
      <?php
    $imagen = $form->get('image-file');
    echo $this->formFile($imagen);
    echo $this->formElementErrors($imagen);
    ?>
</div> 
    

  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
    $submit = $form->get('submit');
    echo $this->formInput($submit);
    echo $this->formElementErrors($submit);
    ?>
    </div>
  </div>
<?php echo $this->form()->openTag($form); ?>



<!-- CONTENIDO DE CLIENTES -->     
</div>
</div>
</div>
</div>
</div>
</div>     