
 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Lote';
 $subtitle= 'Lotes actuales';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">
                        <p>Lista de Lotes actualmente registrados. Eliga editar o Eliminar</p>
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
        <hr>
        <a class="btn btn-success btn-sm" href="<?php echo $this->url('admin-lote', array('action'=>'agregar'));?>">Agregar nuevo lote</a>
                    

      <!-- Table -->
                    <div class="table-responsive">
          
                <table class="table table-hover table-condensed">
                    <thead>
                        <tr>
                            <th>Hora</th>
                            <th>Producto</th>
                            <th>Nave</th>
                            <th>Destino</th>
                            <th>Numero entrega</th>
                            <th>Sap Code</th>
                            <th>Numero Lote</th>
                            <th>Condicion</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                            <?php foreach ($this->paginator as $m) : ?>
                            <tr>

                                
                                
                                <td><?php echo $this->escapeHtml($m->hora);?></td>
                                <td><?php echo $this->escapeHtml($m->producto);?></td>
                                <td><?php echo $this->escapeHtml($m->nave);?></td>
                                <td><?php echo $this->escapeHtml($m->destino);?></td>
                                <td><?php echo $this->escapeHtml($m->numero_entrega);?></td>
                                <td><?php echo $this->escapeHtml($m->codigo_sap);?></td>
                                <td><?php echo $this->escapeHtml($m->numero_lote);?></td>
                                <td><?php echo $this->escapeHtml($m->estado);?></td>
                               
                                <td>
                                    <a class="btn btn-warning btn-xs" href="<?php echo $this->url('admin-lote',
                                        array('action'=>'editar', 'id' => $m->id_lote));?>">Editar</a>
                                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('admin-lote',
                                        array('action'=>'borrar', 'id' => $m->id_lote));?>">Borrar</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                    </tbody>
                 </table> 
                        <?php echo $this->paginationControl(
                                    // the paginator object
                                    $this->paginator,
                                    // the scrolling style
                                    'sliding',
                                    // the partial to use to render the control
                                    array('partial/paginator.phtml', 'Admin'),
                                    // the route to link to when a user clicks a control link
                                    array(
                                        'route' => 'admin-contenedor'
                                    )
                                );
                            ?> 
           </div>
                    </div>
                </div>
        </div>
    </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
</div>     
            
            
            
      
 
            
            
            
      