<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Bodegas';
 $subtitle= 'Bodegas actuales';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">
                        <p>Lista de bodegas actualmente registrados. Eliga editar o Eliminar</p>
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Buscar...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
        <hr>
        <a class="btn btn-success btn-sm" href="<?php echo $this->url('admin-bodega', array('action'=>'agregar'));?>">Agregar nuevo Bodega</a>
                    </div>

      <!-- Table -->
                    <div class="table-responsive">
          
                <table class="table table-hover table-condensed">
                    <thead>
                            <tr>
                              <th>Numero de bodega</th>
                              <th>Descripcion</th>
                              
                              <th>&nbsp;</th>
                            </tr>
                    </thead>
                    <tbody>
                            <?php foreach ($this->paginator as $u) : ?>
                            <tr>


                                <td><?php echo $this->escapeHtml($u->nro_bodega);?></td>
                                <td><?php echo $this->escapeHtml($u->descripcion);?></td>
                                
                                <td>
                                    <a class="btn btn-warning btn-sm" href="<?php echo $this->url('admin-bodega',
                                            array('action'=>'editar', 'id' => $u->nro_bodega));?>">Editar</a>
                                   <a class="btn btn-danger btn-sm" href="<?php echo $this->url('admin-bodega',
                                        array('action'=>'borrar', 'id' => $u->nro_bodega));?>">Borrar</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                    </tbody>
                </table>        <hr>
                           <?php echo $this->paginationControl(
                                    // the paginator object
                                    $this->paginator,
                                    // the scrolling style
                                    'sliding',
                                    // the partial to use to render the control
                                    array('partial/paginator.phtml', 'Admin'),
                                    // the route to link to when a user clicks a control link
                                    array(
                                        'route' => 'admin-bodega'
                                    )
                                );
                            ?> 
                    </div>
                </div>
        </div>
    </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
</div>     
<?php
 // add at the end of the file after the table
    