<?php


 $title = 'Clientes';
 $subtitle= 'Editar Cliente';
 $this->headTitle($title);
 ?>

<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">


<!-- CONTENIDO DE CLIENTES -->                        
                        
<?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'admin-cliente',
     array(
         'action' => 'editar',
         'id'     => $this->id,
     )
 ));
 $form->setAttribute('role','form');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>                        
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="organizacion" class="col-sm-2 control-label">Organizacion</label>
    <div class="col-sm-10">
      <?php
    echo $this->formHidden($form->get('id_cliente'));
    $organizacion = $form->get('organizacion');
    echo $this->formInput($organizacion);
    echo $this->formElementErrors($organizacion);
    ?>
    </div>
  </div>
  <div class="form-group">
    <label for="razon_social" class="col-sm-2 control-label">Razon social</label>
    <div class="col-sm-10">
      <?php
    $razon_social = $form->get('razon_social');
    echo $this->formInput($razon_social);
    echo $this->formElementErrors($razon_social);
    ?>
    </div>
  </div>
  <div class="form-group">
    <label for="organizacion" class="col-sm-2 control-label">Rut</label>
    <div class="col-sm-10">
      <?php
    $rut_cliente = $form->get('rut_cliente');
    echo $this->formInput($rut_cliente);
    echo $this->formElementErrors($rut_cliente);
    ?>
    </div>
  </div>
  <div class="form-group">
    <label for="direccion" class="col-sm-2 control-label">Direccion</label>
    <div class="col-sm-10">
      <?php
    $direccion = $form->get('direccion');
    echo $this->formInput($direccion);
    echo $this->formElementErrors($direccion);
    ?>
    </div>
  </div>     
  <div class="form-group">
    <label for="fono_cliente" class="col-sm-2 control-label">Telefono</label>
    <div class="col-sm-10">
      <?php
    $fono_cliente = $form->get('fono_cliente');
    echo $this->formInput($fono_cliente);
    echo $this->formElementErrors($fono_cliente);
    ?>
    </div>
  </div>   
  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
    $submit = $form->get('submit');
    echo $this->formInput($submit);
    echo $this->formElementErrors($submit);
    ?>
    </div>
  </div>
<?php echo $this->form()->openTag($form); ?>



<!-- CONTENIDO DE CLIENTES -->     

</div>
</div>
</div>
</div>
</div>     