
 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Nave';
 $subtitle= 'Editar Nave';
 $this->headTitle($title);
 ?>
 
 
<div class="panel-heading">
    <?php echo $this->escapeHtml($title); ?>
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
             <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $this->escapeHtml($subtitle); ?> </div>
                    <div class="panel-body">

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'admin-nave',
     array(
         'action' => 'editar',
         'id'     => $this->id,
     )
 ));
 $form->setAttribute('role','form');
 $form->setAttribute('class','form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>                        

  <div class="form-group">
    <label for="nombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
      <?php
    echo $this->formHidden($form->get('id_nave'));
    $nombre = $form->get('nombre');
    echo $this->formInput($nombre);
    echo $this->formElementErrors($nombre);
    ?>
    </div>
  </div>
  <div class="form-group">
    <label for="codigo" class="col-sm-2 control-label">Codigo</label>
    <div class="col-sm-10">
      <?php
    $codigo = $form->get('codigo');
    echo $this->formInput($codigo);
    echo $this->formElementErrors($codigo);
    ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
    $submit = $form->get('submit');
    echo $this->formInput($submit);
    echo $this->formElementErrors($submit);
    ?>
    </div>
  </div>
<?php echo $this->form()->openTag($form); ?>



<!-- CONTENIDO DE CLIENTES -->     

</div>
</div>
</div>
</div>
</div>  