<div class="modal fade <?php echo $m->id_cont?>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-personalizado">
                                      <div class="modal-content">
                                          <div class = "modal-header">
                                              <button type="button" class="close" data-dismiss="modal">
                                                  <span aria-hidden="true">x</span>
                                                  <span class="sr-only">Cerrar</span>
                                              </button>
                                            
                                            
                                            <hr>
                                            <h4>Exportador: <?php echo $m->exportador?></h4>
                                            <h4>Producto: <?php echo $m->producto?></h4>
                                          </div>
                                          <div class="modal-body">
                                            <div id="<?php echo $m->id_cont?>" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators">
                                      <li data-target="#<?php echo $m->id_cont?>" data-slide-to="0" class="active"></li>
                                      <li data-target="#<?php echo $m->id_cont?>" data-slide-to="1"></li>
                                      <li data-target="#<?php echo $m->id_cont?>" data-slide-to="2"></li>
                                      
           
                                    </ol>

                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner">
                                      <div class="item active">
                                          <img src="<?php echo $this->basePath('img/contenedor/1.jpg')?>" alt="..." width="100%">
                                        <div class="carousel-caption">
                                          ...
                                        </div>
                                      </div>
                                      <div class="item">
                                        <img src="<?php echo $this->basePath('img/contenedor/2.jpg')?>" alt="..." width="100%">
                                        <div class="carousel-caption">
                                          ...
                                        </div>
                                      </div>
                                        <div class="item">
                                        <img src="<?php echo $this->basePath('img/contenedor/3.jpg')?>" alt="..." width="100%">
                                        <div class="carousel-caption">
                                          ...
                                        </div>
                                      </div>
                                          <div class="item">
                                        <img src="<?php echo $this->basePath('img/contenedor/4.jpg')?>" alt="..." width="100%">
                                        <div class="carousel-caption">
                                          ...
                                        </div>
                                      </div>
                                      ...
                                    </div>

                                    <!-- Controls -->
                                    <a class="left carousel-control" href="#<?php echo $m->id_cont?>" role="button" data-slide="prev">
                                      <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#<?php echo $m->id_cont?>" role="button" data-slide="next">
                                      <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>
                                  </div>
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                            
                                          </div>
                                          </div>
                                    </div>
                                  </div>